Install pandas and matplotlib library

In [2]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install matplotlib

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy
numpy.__version__

'1.24.1'

In [5]:
import numpy as np

In [6]:
np?

Type:        module
String form: <module 'numpy' from 'D:\\All Programs\\anaconda\\envs\\your_venv\\lib\\site-packages\\numpy\\__init__.py'>
File:        d:\all programs\anaconda\envs\your_venv\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-t

In [7]:
import numpy as np

In [8]:
rng = np.random.default_rng(seed=100) # seed for reproducibility

In [9]:
rng

Generator(PCG64) at 0x21CBD049D20

In [10]:
x1 = rng.integers(10, size=6) # one-dimensional array

In [11]:
x1

array([7, 8, 1, 5, 0, 2], dtype=int64)

In [12]:
x2 = rng.integers(10, size=(3, 4)) # two-dimensional array

In [13]:
x2

array([[4, 0, 5, 9],
       [9, 5, 4, 7],
       [9, 9, 0, 6]], dtype=int64)

In [14]:
x3 = rng.integers(10, size=(3, 4, 5)) # three-dimensional array

In [15]:
x3

array([[[7, 1, 5, 9, 6],
        [2, 3, 6, 1, 5],
        [5, 5, 7, 5, 7],
        [9, 1, 5, 1, 7]],

       [[1, 4, 2, 9, 4],
        [9, 8, 3, 4, 3],
        [8, 8, 4, 7, 9],
        [6, 7, 4, 9, 3]],

       [[6, 1, 6, 6, 1],
        [0, 8, 2, 8, 6],
        [1, 0, 1, 8, 4],
        [0, 2, 5, 8, 5]]], dtype=int64)

In [16]:
x1[0]

7

In [17]:
x2

array([[4, 0, 5, 9],
       [9, 5, 4, 7],
       [9, 9, 0, 6]], dtype=int64)

In [18]:
x2[1,2]

4

In [19]:
x2[0, 1]

0

In [20]:
x2[0, 1] = 3
x2

array([[4, 3, 5, 9],
       [9, 5, 4, 7],
       [9, 9, 0, 6]], dtype=int64)

In [21]:
x1[0] = 3.14
x1

array([3, 8, 1, 5, 0, 2], dtype=int64)

In [22]:
x1[0] = 4.638
x1

array([4, 8, 1, 5, 0, 2], dtype=int64)

In [23]:
x1[:3] # first three elements

array([4, 8, 1], dtype=int64)

In [24]:
x1[::2] # every second element

array([4, 1, 0], dtype=int64)

In [25]:
x1[3:] # elements after index 3

array([5, 0, 2], dtype=int64)

In [26]:
x1[1:4] # middle subarray

array([8, 1, 5], dtype=int64)

In [27]:
x1[1::2] # every second element, starting at index 1

array([8, 5, 2], dtype=int64)

In [28]:
x1[::-1] # all elements, reversed

array([2, 0, 5, 1, 8, 4], dtype=int64)

In [29]:
x1[4::-2] # every second element from index 4, reversed

array([0, 1, 4], dtype=int64)

In [30]:
x2

array([[4, 3, 5, 9],
       [9, 5, 4, 7],
       [9, 9, 0, 6]], dtype=int64)

In [31]:
x2[:2, :3] # first two rows & three columns

array([[4, 3, 5],
       [9, 5, 4]], dtype=int64)

In [32]:
x2[:3, ::2] # three rows, every second column

array([[4, 5],
       [9, 4],
       [9, 0]], dtype=int64)

In [33]:
x2[::-1, ::-1] # all rows & columns, reversed

array([[6, 0, 9, 9],
       [7, 4, 5, 9],
       [9, 5, 3, 4]], dtype=int64)

In [34]:
x2[:, 0] # first column of x2

array([4, 9, 9], dtype=int64)

In [35]:
data = np.arange(1, 10).reshape(3, 3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [37]:
x.reshape((1,3)) # row vector via reshape

array([[1, 2, 3]])

In [38]:
x.reshape((3, 1)) #column vector via reshape

array([[1],
       [2],
       [3]])

In [39]:
x[np.newaxis, :] # row vector via newaxis

array([[1, 2, 3]])

In [40]:
x[:, np.newaxis] # column vector via newaxis

array([[1],
       [2],
       [3]])

In [41]:
x = np.array([1,2,3])
y = np.array([3,2,1])

np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [42]:
z = np.array([10,20,30])
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 10, 20, 30])

In [43]:
data = np.array([[1, 2, 3],
 				[4, 5, 6]])
#concatenate along the first axis
np.concatenate([data, data])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
# concatenate along the second axis (zero-indexed)
np.concatenate([data, data], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [45]:
# vertically stack the arrays
np.vstack([x, data])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [46]:
# horizontally stack the arrays
y = np.array([[10],[20]])
np.hstack([data, y])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20]])

In [47]:
x = [1,2,3,6,7,8,11,12,13]
x1, x2 = np.split(x, [2])
x1,x2

(array([1, 2]), array([ 3,  6,  7,  8, 11, 12, 13]))

In [48]:
data = np.arange(16).reshape(4,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
upper, lower = np.vsplit(data, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [50]:
left, right = np.hsplit(data, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [51]:
import numpy as np
rng = np.random.default_rng(seed=1701)
rng

Generator(PCG64) at 0x21CBD049E00

In [52]:
import numpy as np
rng = np.random.default_rng(seed=1701)

def compute_reciprocals(values):
    output= np.empty(len(values))
    for row in range(len(values)):
        output[row] = 1.0 / values[row]
    return output
    
values = rng.integers(1, 10, size=5)
compute_reciprocals(values)

array([0.11111111, 0.25      , 1.        , 0.33333333, 0.125     ])

In [53]:
print(compute_reciprocals(values))

[0.11111111 0.25       1.         0.33333333 0.125     ]


In [54]:
print(1.0 / values)

[0.11111111 0.25       1.         0.33333333 0.125     ]


In [55]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [56]:
x = np.arange(9).reshape((3, 3))

In [57]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
x =  2 ** x
x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

NumPy Basics: Arrays and Vectorized Computation

In [59]:
data = np.array([[1.5,  -0.1, 3], [0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [60]:
data * 10

array([[ 15.,  -1.,  30.],
       [  0., -30.,  65.]])

In [61]:
data + data

array([[ 3. , -0.2,  6. ],
       [ 0. , -6. , 13. ]])

In [62]:
data.shape

(2, 3)

In [63]:
data.dtype

dtype('float64')

In [64]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [65]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] # nested 
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
arr2.ndim

2

In [67]:
arr2.shape

(2, 4)

In [68]:
arr1.dtype

dtype('float64')

In [69]:
arr2.dtype

dtype('int32')

In [70]:
np.zeros(4)

array([0., 0., 0., 0.])

In [71]:
np.arange(5)

array([0, 1, 2, 3, 4])

Data Types for ndarrays

In [72]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [73]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [74]:
arr1.dtype

dtype('float64')

In [75]:
arr2.dtype

dtype('int32')

In [76]:
arr = np.array([1,2,3,4,5])

In [77]:
arr.dtype

dtype('int32')

In [78]:
float_arr = arr.astype(np.float64)
float_arr

array([1., 2., 3., 4., 5.])

In [79]:
float_arr.dtype

dtype('float64')

In [80]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [81]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [82]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [83]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)

In [84]:
 numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

Boolean Indexing

In [85]:
names = np.array(["Naj", "Ram", "Davis", "Naj", "Davis", "Ram", "Ram"])


In [86]:
names == "Naj"

array([ True, False, False,  True, False, False, False])

In [87]:
names != "Davis"

array([ True,  True, False,  True, False,  True,  True])

In [88]:
~(names == "Davis")

array([ True,  True, False,  True, False,  True,  True])

In [89]:
mask = (names == "Davis") | (names == "Ram")
mask

array([False,  True,  True, False,  True,  True,  True])

In [90]:
arr = np.zeros((4, 4))

for row in range(4):
    arr[row] = row

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [91]:
arr[[1, 2, 3, 0]]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.]])

In [92]:
arr = np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [93]:
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [94]:
arr.reshape((4,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

Transposing Array and Swapping Axes

In [95]:
arr = np.arange(8).reshape((4,2))
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [96]:
arr.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [97]:
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [98]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [99]:
arr.swapaxes(0, 1)

array([[0, 3],
       [1, 4],
       [2, 5]])

Pseudo random number generation

In [100]:
samples = np.random.standard_normal(size=(4,4))
samples

array([[ 0.33952447, -0.40366676,  0.87683281,  0.43591199],
       [-0.06785095,  0.2677009 , -1.5488221 , -1.80390523],
       [-0.41262385,  0.15743205, -0.74318164, -1.52287771],
       [-3.35660574,  1.1106466 ,  0.4443457 ,  0.41461203]])

In [101]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [103]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [104]:
x = rng.standard_normal(7)
x

array([-0.81928256,  0.69156442, -1.62453268,  1.50806312, -1.22449846,
        1.22696072, -1.05013046])

In [105]:
y = rng.standard_normal(7)
y

array([ 0.62509363,  0.09693023,  0.62776415, -0.28565182,  1.49678665,
       -0.76768541, -0.3942867 ])

In [107]:
np.maximum(x,y)

array([ 0.62509363,  0.69156442,  0.62776415,  1.50806312,  1.49678665,
        1.22696072, -0.3942867 ])

In [113]:
arr = np.arange(8)

In [114]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [115]:
arr.mean()

3.5

In [117]:
np.mean(arr)

3.5

In [118]:
arr.sum()

28

In [120]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [123]:
arr1 = np.arange(6).reshape((2,3))

In [124]:
arr1

array([[0, 1, 2],
       [3, 4, 5]])

In [126]:
arr1.mean(axis=1)

array([1., 4.])

In [130]:
arr1.sum(axis=0)

array([3, 5, 7])

In [131]:
arr1.sum(axis=1)

array([ 3, 12])

In [133]:
arr2 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [134]:
arr2.cumsum(axis=0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

#### Sorting

In [135]:
arr = rng.standard_normal(6)
arr

array([-1.35693505,  0.33524959,  0.57442768,  1.62016911,  0.33395176,
       -1.02906713])

In [136]:
arr.sort()

In [137]:
arr

array([-1.35693505, -1.02906713,  0.33395176,  0.33524959,  0.57442768,
        1.62016911])

In [138]:
arr = rng.standard_normal((2,3))
arr

array([[-0.94266623,  0.38365532,  0.25423793],
       [ 1.36108696,  1.25474959, -0.05637126]])

In [139]:
arr.sort(axis=0)
arr

array([[-0.94266623,  0.38365532, -0.05637126],
       [ 1.36108696,  1.25474959,  0.25423793]])

In [141]:
arr.sort(axis=1)
arr

array([[-0.94266623, -0.05637126,  0.38365532],
       [ 0.25423793,  1.25474959,  1.36108696]])

##### File Input and Output
save data

In [142]:
arr = np.arange(10)

In [143]:
np.save("some defined array", arr)

load data

In [145]:
np.load("some defined array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
np.savez("array_archive.npz", a=arr, b=arr)

In [147]:
arch = np.load("array_archive.npz")

In [148]:
arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])