In [39]:
'''
NumPy:
- extension package to Python for multi-dimensional arrays
- closer to hardware (efficiency)
- designed for scientific computation
- also known as array oriented computing
- 1D list array is called vector/array
- 2D list array is called matrix
- 3D --> cube
'''

'\nNumPy:\n- extension package to Python for multi-dimensional arrays\n- closer to hardware (efficiency)\n- designed for scientific computation\n- also known as array oriented computing\n- 1D list array is called vector/array\n- 2D list array is called matrix\n- 3D --> cube\n'

In [1]:
import numpy as np

a = np.array([0,1,2,3,4]) # 1-D array
print(a)

[0 1 2 3 4]


In [2]:
# print dimension
a.ndim

1

In [3]:
# shape
a.shape

(5,)

In [4]:
#2D and 3D array
b = np.array([[1,2,3], [4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b.shape

(2, 3)

In [9]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]]) # list -> list -> list
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [10]:
c.ndim

3

In [11]:
c.shape # row and column of two. (l,b,h) of 2

(2, 2, 2)

In [ ]:
# 1D array --> vector/array
# 2D array --> matrix
# nD array (3D, 4D, 5D,...nD) --> Tensor

Function for creating arrays

In [14]:
# using arrange function 
a = np.arange(10) # 0.... n-1
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
b = np.arange(1,10,2) # start, end, step
b

array([1, 3, 5, 7, 9])

In [16]:
#using linear space
a = np.linspace(0,1,6) # start, end, number of points
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [17]:
#common arrays

a = np.ones((3,3)) # tuple inside function creating 3,3 matrix
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
a = np.zeros((3,3)) # tuple inside function creating 3,3 matrix
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.eye(3) #returns 2-D array with ones on the diagonal[identity matrix] and zero elsewhere


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
#create array using diag function
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [21]:
np.diag(a) #extract diagonal

array([1, 2, 3, 4])

In [23]:
#create array using random
a = np.random.rand(4) # random --> module and rand --> function with 4 random numbers
a

array([0.26889244, 0.19904535, 0.00740671, 0.57157537])

DataTypes

In [24]:
a = np.arange(10)
a.dtype

dtype('int32')

In [25]:
# we can explicitly specify which data-type we want

a = np.arange(10, dtype= 'float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
b = np.array([True, False])
print(b.dtype)

bool


Indexing and Slicing

In [27]:
a = np.arange(10)

print(a[2]) # not index 2 location 2 so comes 2

2


In [28]:
#for multidimensional arrays, indexes are tuples of integers
a = np.diag([1,2,3])

print(a[2,2]) # a of 2nd row and 2nd column that starting with 0 index i.e. last row and last col

3


Slicing

In [29]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a[1:8:2] # [#start index : end index : step]

array([1, 3, 5, 7])

In [31]:
# we can also combine assignment and slicing

a = np.arange(10)
a[5:] = 10 #printing 10 from index 5 to 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [33]:
b = np.arange(5)
a[5:] = b[::-1] #::-1 --> : (denotes start = 0), :-1 (reverse order)
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

Fancy Indexing:


NumPy arrays can be indexed with slices but also with boolean or integer arrays (masks).
this method is called fancy indexing. it creates copies not views.

In [34]:
# using boolean mask

a = np.random.randint(0, 30, 15) #creating random number between 0 to 30 with 15 numbers

a

array([ 7,  8, 13, 16,  2, 27, 19,  6, 25, 23, 22, 24, 18,  9, 20])

In [35]:
mask = (a % 2 == 0)
extract_from_a = a[mask]    #mask creates copy not view
extract_from_a

array([ 8, 16,  2,  6, 22, 24, 18, 20])

In [36]:
# printing all the even number to -1

a[mask] = -1
a

array([ 7, -1, 13, -1, -1, 27, 19, -1, 25, 23, -1, -1, -1,  9, -1])

Indexing with an array of integers

In [37]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
# new values can be assigned
a[[7, 9]] = -200 # replace index 7 and 9 with -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])

In [40]:
# scalar array

a = np.array([1,2,3,4])

a+ 1

array([2, 3, 4, 5])

In [41]:
a**2

array([ 1,  4,  9, 16])

In [42]:
#Computing sum
x = np.array([1,2,3,4])
np.sum(x)

10

In [43]:
#sum by rows and columns

x = np.array([[1,1], [2,2]])
x

array([[1, 1],
       [2, 2]])

In [44]:
x.sum(axis=0) #columns first dimension
# axis = 0 is column and 1 is row

array([3, 3])

In [45]:
x.sum(axis=1) # row wise sum

array([2, 4])

In [47]:
x = np.array([1,3,2])
x.min()

1

In [48]:
x.max()

3

In [49]:
x.argmin()

0

In [50]:
x.argmax()

1

Statistics

In [51]:
x = np.array([1,2,3,1])
y = np.array([[1,2,3], [5,6,1]])
x.mean()

1.75

In [52]:
np.median(x)

1.5

In [53]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [54]:
x.std()

0.82915619758885

Array Manipulation

Flattening

In [57]:
a = np.array([[1,2,3], [4,5,6]])
a.ravel() # Converting 2D array to 1D

array([1, 2, 3, 4, 5, 6])

In [58]:
a.T #transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [59]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

Reshaping: Inverse operation to flattening.

In [60]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [61]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [62]:
b = b.reshape((2,3))
b #gets original 'a' matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
#Resizing
a = np.arange(4)
a.resize((8,)) # resizing with 0 after 4 position
a 

array([0, 1, 2, 3, 0, 0, 0, 0])

Sorting Data

In [64]:
#sorting along an axis
# axis =0 --> column
# axis =1 --> row
a = np.array([[5,4,6], [2,3,2]])
b = np.sort(a, axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [65]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [66]:
#sorting with fancy indexing
a= np.array([4,3,1,2])
i = np.argsort(a) #second index comes first, last index comes second and so on
i

array([2, 3, 1, 0], dtype=int64)

In [67]:
# i = [2,3,1,0]
a[i] # a ->2 value is 1, a->3 value is 2 and so on

array([1, 2, 3, 4])